table Dim_Date
	lineageTag: 41dd647c-0e02-4586-937b-a843d24465b1

	column Year
		dataType: int64
		formatString: 0
		lineageTag: f11d8359-4211-480b-80aa-95875222c950
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 93fca91d-2873-4028-b8af-883a9726b148
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 818aef52-f61b-473c-be5d-c0305aac49a5
			defaultHierarchy: LocalDateTable_2a5a8e18-2bfd-4108-85a5-726946390244.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YearLabel
		dataType: string
		lineageTag: 611274d7-cc69-40ed-801b-9d89ed5daac0
		summarizeBy: none
		sourceColumn: YearLabel

		annotation SummarizationSetBy = Automatic

	column Decade
		dataType: string
		lineageTag: f1695482-bfda-4253-8aa1-4cdcd985b354
		summarizeBy: none
		sourceColumn: Decade

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 0f548982-a7a2-4532-b1e3-d8944e7193fb
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\kelangthanghocIT\UTH\capstone-asean_overview_analysis\02_Data\Cleaned\Dim_Date.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", Int64.Type}, {"Date", type date}, {"YearLabel", type text}, {"Decade", type text}, {"Period", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

