table Fact_ASEAN_Indicators
	lineageTag: d5338223-a8c5-4304-afb5-e67c1d956167

	column CountryCode
		dataType: string
		lineageTag: 15381324-5184-467b-8efc-1ff3addbb963
		summarizeBy: none
		sourceColumn: CountryCode

		annotation SummarizationSetBy = Automatic

	column SeriesCode
		dataType: string
		lineageTag: e51905a4-3ef7-4e31-b663-6d2ca4350709
		summarizeBy: none
		sourceColumn: SeriesCode

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: e8afd99d-9391-4c2d-9abf-1feb8792e2bd
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 88c662ac-8033-4ad0-854a-47336413dd9a
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DateKey = DATE([Year], 1, 1)
		dataType: dateTime
		isHidden
		formatString: dd/MM/yyyy
		lineageTag: 0e123399-8ec4-4d00-840c-8e292870ce44
		summarizeBy: none

	partition Fact_ASEAN_Indicators = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\kelangthanghocIT\UTH\capstone-asean_overview_analysis\02_Data\Cleaned\Fact_ASEAN_Indicators.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CountryCode", type text}, {"SeriesCode", type text}, {"Year", Int64.Type}, {"Value", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

