table Fact_ASEAN_Tourism_Flow
	lineageTag: f3843a81-6310-47f8-a2b0-4d7efa377134

	column DestinationCountryCode
		dataType: string
		lineageTag: 00605167-c2d5-42f2-b309-2004f609d32b
		summarizeBy: none
		sourceColumn: DestinationCountryCode

		annotation SummarizationSetBy = Automatic

	column OriginCountryCode
		dataType: string
		lineageTag: cca3a83c-170e-4a58-bf54-dd9e7bdc9c3d
		summarizeBy: none
		sourceColumn: OriginCountryCode

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 7a64fa93-73d3-4d9a-b318-c16191d6b936
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Visitors
		dataType: int64
		formatString: 0
		lineageTag: ef5ec506-e63d-4385-921d-bfa2b73c2ce3
		summarizeBy: sum
		sourceColumn: Visitors

		annotation SummarizationSetBy = Automatic

	column DateKey = DATE([Year], 1, 1)
		dataType: dateTime
		isHidden
		formatString: dd/MM/yyyy
		lineageTag: abc55b5f-2373-4c7a-ad7d-2b4aee24050d
		summarizeBy: none

	partition Fact_ASEAN_Tourism_Flow = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\kelangthanghocIT\UTH\capstone-asean_overview_analysis\02_Data\Cleaned\Fact_ASEAN_Tourism_Flow.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DestinationCountryCode", type text}, {"OriginCountryCode", type text}, {"Year", Int64.Type}, {"Visitors", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

